import Testing
import Foundation
@testable import Scout

/// Each test builds a throwaway `home` and asserts the matrix row from spec §10.
@Suite("EngineLocator")
struct EngineLocatorTests {
    let fm = FileManager.default

    func makeHome() throws -> EngineLayout {
        let home = fm.temporaryDirectory.appendingPathComponent("engine-locator-\(UUID().uuidString)")
        try fm.createDirectory(at: home, withIntermediateDirectories: true)
        return EngineLayout(home: home)
    }

    func executable(_ url: URL) throws {
        try fm.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "#!/bin/sh\n".write(to: url, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    }

    func pluginTree(_ root: URL, version: String) throws {
        try fm.createDirectory(at: root.appending(path: ".claude-plugin"), withIntermediateDirectories: true)
        try #"{"name": "scout", "version": "\#(version)"}"#.write(to: root.appending(path: ".claude-plugin/plugin.json"), atomically: true, encoding: .utf8)
    }

    func pointer(_ layout: EngineLayout, version: String, managedBy: String, vault: String? = nil) throws {
        let root = layout.engineRoot(version: version)
        let json = """
        {"schema_version": 1, "version": "\(version)", "engine_root": "\(root.path)",
         "python": "\(layout.venv(version: version).path)/bin/python", "scoutctl": "\(layout.scoutctl(version: version).path)",
         "vault": "\(vault ?? layout.home.appending(path: "Scout").path)", "managed_by": "\(managedBy)", "written_at": "2026-09-08T00:00:00Z"}
        """
        try fm.createDirectory(at: layout.stateDir, withIntermediateDirectories: true)
        try json.write(to: layout.pointerURL, atomically: true, encoding: .utf8)
    }

    @Test func nothingOnDiskIsNotInstalled() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        #expect(EngineLocator(layout: layout).locate() == .notInstalled)
    }

    @Test func appManagedPointerIsManaged() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.engineRoot(version: "0.10.0"), version: "0.10.0")
        try executable(layout.scoutctl(version: "0.10.0"))
        try pointer(layout, version: "0.10.0", managedBy: "scout-app")
        guard case .managed(let install, let bootstrapped) = EngineLocator(layout: layout).locate() else {
            Issue.record("expected .managed"); return
        }
        #expect(bootstrapped)
        #expect(install.version == "0.10.0")
        #expect(install.scoutctl == layout.scoutctl(version: "0.10.0"))
        #expect(install.vault == layout.home.appending(path: "Scout"))
    }

    @Test func pointerFromOtherManagerIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.engineRoot(version: "0.10.0"), version: "0.10.0")
        try executable(layout.scoutctl(version: "0.10.0"))
        try pointer(layout, version: "0.10.0", managedBy: "install.sh")
        #expect(EngineLocator(layout: layout).locate().externalSource == .installSh)
    }

    @Test func pointerWithMissingScoutctlIsBroken() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pointer(layout, version: "0.10.0", managedBy: "scout-app")
        guard case .broken(_, let reason) = EngineLocator(layout: layout).locate() else { Issue.record("expected .broken"); return }
        #expect(reason.contains("scoutctl"))
    }

    @Test func conventionalLayoutWithoutPointerIsManagedButNotBootstrapped() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.engineRoot(version: "0.10.0"), version: "0.10.0")
        try fm.createSymbolicLink(at: layout.currentEngineLink, withDestinationURL: layout.engineRoot(version: "0.10.0"))
        try executable(layout.scoutctl(version: "0.10.0"))
        guard case .managed(let install, let bootstrapped) = EngineLocator(layout: layout).locate() else { Issue.record("expected .managed"); return }
        #expect(!bootstrapped)
        #expect(install.version == "0.10.0")
    }

    @Test func shimPointingAtALiveVenvIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        let real = layout.home.appending(path: "somewhere/.venv/bin/scoutctl")
        try executable(real)
        try pluginTree(layout.home.appending(path: "somewhere"), version: "0.9.0")
        try fm.createDirectory(at: layout.localBin, withIntermediateDirectories: true)
        try "#!/bin/sh\n# scout-plugin scoutctl shim — regenerated by `scoutctl bootstrap install/upgrade`.\nexec \"\(real.path)\" \"$@\"\n"
            .write(to: layout.shimURL, atomically: true, encoding: .utf8)
        let state = EngineLocator(layout: layout).locate()
        #expect(state.externalSource == .shim)
        #expect(state.install?.version == "0.9.0")
    }

    @Test func marketplaceCacheInstallIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        let cache = layout.claudePluginsDir.appending(path: "cache/scout-plugin/scout/0.9.0")
        try pluginTree(cache, version: "0.9.0")
        try executable(cache.appending(path: ".venv/bin/scoutctl"))
        try fm.createDirectory(at: layout.claudePluginsDir, withIntermediateDirectories: true)
        try #"{"version": 2, "plugins": {"scout@scout-plugin": [{"version": "0.9.0", "installPath": "\#(cache.path)"}]}}"#
            .write(to: layout.claudePluginsDir.appending(path: "installed_plugins.json"), atomically: true, encoding: .utf8)
        #expect(EngineLocator(layout: layout).locate().externalSource == .marketplaceCache)
    }

    @Test func devCheckoutIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.devCheckout, version: "0.9.0")
        try executable(layout.devCheckout.appending(path: ".venv/bin/scoutctl"))
        #expect(EngineLocator(layout: layout).locate().externalSource == .devCheckout)
    }

    @Test func parseShimTargetRequiresTheMarker() {
        #expect(EngineLocator.parseShimTarget("#!/bin/sh\n# scout-plugin scoutctl shim\nexec \"/x/bin/scoutctl\" \"$@\"\n") == "/x/bin/scoutctl")
        #expect(EngineLocator.parseShimTarget("#!/bin/sh\nexec \"/x/bin/scoutctl\" \"$@\"\n") == nil)
    }
}

extension EngineState {
    var externalSource: ExternalSource? {
        if case .external(_, let s) = self { return s }
        return nil
    }
}
