import Testing
import Foundation
@testable import Scout

/// Each test builds a throwaway `home` and asserts the matrix row from spec §10.
@Suite("EngineLocator")
struct EngineLocatorTests {
    let fm = FileManager.default

    func makeHome() throws -> EngineLayout {
        let home = fm.temporaryDirectory.appendingPathComponent("engine-locator-\(UUID().uuidString)")
        try fm.createDirectory(at: home, withIntermediateDirectories: true)
        return EngineLayout(home: home)
    }

    func executable(_ url: URL) throws {
        try fm.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try "#!/bin/sh\n".write(to: url, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    }

    func pluginTree(_ root: URL, version: String) throws {
        try fm.createDirectory(at: root.appending(path: ".claude-plugin"), withIntermediateDirectories: true)
        try #"{"name": "scout", "version": "\#(version)"}"#.write(to: root.appending(path: ".claude-plugin/plugin.json"), atomically: true, encoding: .utf8)
    }

    func pointer(_ layout: EngineLayout, version: String, managedBy: String, vault: String? = nil) throws {
        let root = layout.engineRoot(version: version)
        let json = """
        {"schema_version": 1, "version": "\(version)", "engine_root": "\(root.path)",
         "python": "\(layout.venv(version: version).path)/bin/python", "scoutctl": "\(layout.scoutctl(version: version).path)",
         "vault": "\(vault ?? layout.home.appending(path: "Scout").path)", "managed_by": "\(managedBy)", "written_at": "2026-09-08T00:00:00Z"}
        """
        try fm.createDirectory(at: layout.stateDir, withIntermediateDirectories: true)
        try json.write(to: layout.pointerURL, atomically: true, encoding: .utf8)
    }

    @Test func nothingOnDiskIsNotInstalled() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        #expect(EngineLocator(layout: layout).locate() == .notInstalled)
    }

    @Test func appManagedPointerIsManaged() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.engineRoot(version: "0.10.0"), version: "0.10.0")
        try executable(layout.scoutctl(version: "0.10.0"))
        try pointer(layout, version: "0.10.0", managedBy: "scout-app")
        guard case .managed(let install, let bootstrapped) = EngineLocator(layout: layout).locate() else {
            Issue.record("expected .managed"); return
        }
        #expect(bootstrapped)
        #expect(install.version == "0.10.0")
        #expect(install.scoutctl == layout.scoutctl(version: "0.10.0"))
        #expect(install.vault == layout.home.appending(path: "Scout"))
    }

    @Test func pointerFromOtherManagerIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.engineRoot(version: "0.10.0"), version: "0.10.0")
        try executable(layout.scoutctl(version: "0.10.0"))
        try pointer(layout, version: "0.10.0", managedBy: "install.sh")
        #expect(EngineLocator(layout: layout).locate().externalSource == .installSh)
    }

    @Test func pointerWithMissingScoutctlIsBroken() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pointer(layout, version: "0.10.0", managedBy: "scout-app")
        guard case .broken(_, let reason) = EngineLocator(layout: layout).locate() else { Issue.record("expected .broken"); return }
        #expect(reason.contains("scoutctl"))
    }

    @Test func conventionalLayoutWithoutPointerIsManagedButNotBootstrapped() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.engineRoot(version: "0.10.0"), version: "0.10.0")
        try fm.createSymbolicLink(at: layout.currentEngineLink, withDestinationURL: layout.engineRoot(version: "0.10.0"))
        try executable(layout.scoutctl(version: "0.10.0"))
        guard case .managed(let install, let bootstrapped) = EngineLocator(layout: layout).locate() else { Issue.record("expected .managed"); return }
        #expect(!bootstrapped)
        #expect(install.version == "0.10.0")
    }

    @Test func shimPointingAtALiveVenvIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        let real = layout.home.appending(path: "somewhere/.venv/bin/scoutctl")
        try executable(real)
        try pluginTree(layout.home.appending(path: "somewhere"), version: "0.9.0")
        try fm.createDirectory(at: layout.localBin, withIntermediateDirectories: true)
        try "#!/bin/sh\n# scout-plugin scoutctl shim — regenerated by `scoutctl bootstrap install/upgrade`.\nexec \"\(real.path)\" \"$@\"\n"
            .write(to: layout.shimURL, atomically: true, encoding: .utf8)
        let state = EngineLocator(layout: layout).locate()
        #expect(state.externalSource == .shim)
        #expect(state.install?.version == "0.9.0")
    }

    /// The other venv layout `installIfVenv` (and the engine's own launcher)
    /// accepts: `<root>/engine/.venv/bin/scoutctl`. The shim's root must be
    /// the plugin root (where `.claude-plugin/plugin.json` lives), not
    /// `<root>/engine`, or the version reads "—" and update checks can't run.
    @Test func shimPointingAtAnEngineSubdirVenvResolvesThePluginRoot() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        let pluginRoot = layout.home.appending(path: "Code/example-org/scout-plugin")
        let real = pluginRoot.appending(path: "engine/.venv/bin/scoutctl")
        try executable(real)
        try pluginTree(pluginRoot, version: "0.11.2")
        try fm.createDirectory(at: layout.localBin, withIntermediateDirectories: true)
        try "#!/bin/sh\n# scout-plugin scoutctl shim — regenerated by `scoutctl bootstrap install/upgrade`.\nexec \"\(real.path)\" \"$@\"\n"
            .write(to: layout.shimURL, atomically: true, encoding: .utf8)
        let state = EngineLocator(layout: layout).locate()
        #expect(state.externalSource == .shim)
        #expect(state.install?.root.path == pluginRoot.path)
        #expect(state.install?.version == "0.11.2")
        #expect(state.install?.scoutctl.path == real.path)
    }

    /// Maintainer decision (2026-10-04): no pip/pipx/Homebrew/conda/`$PATH`
    /// fallbacks. A stray `scoutctl` — an editable install in a conda env, a
    /// pipx venv, or a plain executable at the shim path without the shim
    /// marker — is not an engine: the locator says `.notInstalled`, so the
    /// gate and the copyable next step show instead of a silent wrong engine.
    @Test func strayScoutctlInstallsAreNotAnEngine() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        for stray in ["miniconda3/bin/scoutctl", "anaconda3/bin/scoutctl", ".local/pipx/venvs/scout/bin/scoutctl",
                      "Library/Python/3.12/bin/scoutctl", "scout-plugin/bin/scoutctl"] {
            try executable(layout.home.appending(path: stray))
        }
        try executable(layout.shimURL)  // `#!/bin/sh` only: no shim marker
        #expect(EngineLocator(layout: layout).locate() == .notInstalled)
    }

    /// The maintainer's own layout: a scout-plugin checkout at the dev path
    /// with its venv at `<root>/.venv` or `<root>/engine/.venv`, found either
    /// through the shim or (no shim) as the dev checkout. Every route must
    /// land on the checkout root and read a real version, never "—".
    @Test("dev checkout resolves root and version", arguments: [".venv", "engine/.venv"], [true, false])
    func devCheckoutLayoutsReadTheRealVersion(venv: String, viaShim: Bool) throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        let real = layout.devCheckout.appending(path: "\(venv)/bin/scoutctl")
        try executable(real)
        try pluginTree(layout.devCheckout, version: "0.11.1")
        if viaShim {
            try fm.createDirectory(at: layout.localBin, withIntermediateDirectories: true)
            try "#!/bin/sh\n# scout-plugin scoutctl shim\nexec \"\(real.path)\" \"$@\"\n"
                .write(to: layout.shimURL, atomically: true, encoding: .utf8)
        }
        let state = EngineLocator(layout: layout).locate()
        #expect(state.externalSource == (viaShim ? .shim : .devCheckout))
        #expect(state.install?.root.standardizedFileURL.path == layout.devCheckout.standardizedFileURL.path)
        #expect(state.install?.scoutctl.path == real.path)
        #expect(state.install?.version == "0.11.1")
        #expect(EngineSettingsModel(state: state, doctor: nil, lastError: nil, bundledVersion: nil).installedVersionLabel == "0.11.1")
    }

    @Test func marketplaceCacheInstallIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        let cache = layout.claudePluginsDir.appending(path: "cache/scout-plugin/scout/0.9.0")
        try pluginTree(cache, version: "0.9.0")
        try executable(cache.appending(path: ".venv/bin/scoutctl"))
        try fm.createDirectory(at: layout.claudePluginsDir, withIntermediateDirectories: true)
        try #"{"version": 2, "plugins": {"scout@scout-plugin": [{"version": "0.9.0", "installPath": "\#(cache.path)"}]}}"#
            .write(to: layout.claudePluginsDir.appending(path: "installed_plugins.json"), atomically: true, encoding: .utf8)
        #expect(EngineLocator(layout: layout).locate().externalSource == .marketplaceCache)
    }

    @Test func devCheckoutIsExternal() throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.devCheckout, version: "0.9.0")
        try executable(layout.devCheckout.appending(path: ".venv/bin/scoutctl"))
        #expect(EngineLocator(layout: layout).locate().externalSource == .devCheckout)
    }

    /// `EngineLocator` must be safe to call off the main actor (Task B3 runs
    /// `locate()` from `Task.detached`); this fails to compile if the type
    /// silently regains `@MainActor` isolation under this project's
    /// `-default-isolation=MainActor` build setting.
    @Test func locatesFromADetachedTask() async throws {
        let layout = try makeHome()
        defer { try? fm.removeItem(at: layout.home) }
        try pluginTree(layout.devCheckout, version: "0.9.0")
        try executable(layout.devCheckout.appending(path: ".venv/bin/scoutctl"))
        let state = await Task.detached { EngineLocator(layout: layout).locate() }.value
        #expect(state.externalSource == .devCheckout)
    }

    @Test func parseShimTargetRequiresTheMarker() {
        #expect(EngineLocator.parseShimTarget("#!/bin/sh\n# scout-plugin scoutctl shim\nexec \"/x/bin/scoutctl\" \"$@\"\n") == "/x/bin/scoutctl")
        #expect(EngineLocator.parseShimTarget("#!/bin/sh\nexec \"/x/bin/scoutctl\" \"$@\"\n") == nil)
    }
}

extension EngineState {
    var externalSource: ExternalSource? {
        if case .external(_, let s) = self { return s }
        return nil
    }
}
