import Foundation
import Combine
import OSLog
import SwiftUI

/// Loads `.scout-logs/connector-calls-*.jsonl` and `connector-alerts.log`
/// from the given logs directory and publishes:
/// 1. A `ConnectorHealthMatrix` (connectors × recent sessions).
/// 2. `activeAlerts`: non-acked `ConnectorAlert`s from the log.
///
/// The connector roster (`defaultConnectors`) is sourced from
/// `connectors.snapshot.json`, the JSON projection of scout-plugin's
/// `connectors.yaml` (Plan 4 Task 8). The snapshot is generated by
/// `scoutctl connectors snapshot` and lives canonically at
/// `~/scout-plugin/engine/scout/connectors.snapshot.json`. When the snapshot
/// can't be loaded, we fall back to a hardcoded list AND emit a noisy
/// log/banner so the operator knows to regenerate.
///
/// Shell scripts remain the source of truth for *which* alerts should fire
/// (`connector-health-report.sh` owns the 14-day sustained-state logic).
/// This service does not re-implement that logic — it only reads and
/// renders.
@MainActor
final class ConnectorHealthService: ObservableObject {
    @Published private(set) var matrix: ConnectorHealthMatrix
    @Published private(set) var activeAlerts: [ConnectorAlert] = []
    /// Set to a non-nil string when the snapshot couldn't be loaded and we're
    /// running on the hardcoded fallback list. Surface this in the UI so the
    /// operator notices that the cross-repo sync slipped.
    @Published private(set) var rosterFallbackReason: String? = nil

    private let logsDirectory: URL
    private let ackStore: ConnectorAckStore
    private let fileEvents: any FileSystemEventSource
    private let connectors: [String]
    private var watchTask: Task<Void, Never>?
    /// Memoises per-file parses so an append to today's log doesn't re-read
    /// two weeks of immutable history.
    private var parseCache = ConnectorCallCache()

    private static let log = Logger(subsystem: "com.scout.Scout", category: "ConnectorHealth")

    init(
        logsDirectory: URL,
        ackStoreURL: URL,
        fileEvents: any FileSystemEventSource,
        connectors: [String]? = nil,
        snapshotURL: URL? = nil
    ) {
        self.logsDirectory = logsDirectory
        self.ackStore = ConnectorAckStore(fileURL: ackStoreURL)
        self.fileEvents = fileEvents

        if let connectors {
            // Explicit override — primarily for tests.
            self.connectors = connectors
            self.rosterFallbackReason = nil
        } else {
            let url = snapshotURL ?? Self.defaultSnapshotURL
            switch Self.loadRoster(from: url) {
            case .success(let keys):
                self.connectors = keys
                self.rosterFallbackReason = nil
            case .failure(let err):
                let msg = "Connector roster snapshot missing — run `scoutctl connectors snapshot` in scout-plugin. (\(err.message))"
                Self.log.error("\(msg, privacy: .public)")
                self.connectors = Self.fallbackConnectors
                self.rosterFallbackReason = msg
            }
        }

        self.matrix = ConnectorHealthMatrix(calls: [], connectors: self.connectors)
    }

    // MARK: - Roster loading

    /// Production default: the snapshot bundled inside Scout.app
    /// (`Scout/Resources/connectors.snapshot.json`). Falls back to the
    /// scout-plugin git clone at `~/scout-plugin/engine/scout/...` for the
    /// dev case where someone is working on both repos and wants edits to
    /// the canonical YAML → regenerated snapshot to flow through without
    /// rebuilding the app.
    ///
    /// Bundling fixes the friend-install regression: users who install
    /// scout-plugin via Claude Code's plugin manager get it under
    /// `~/.claude/plugins/...` rather than `~/scout-plugin/`, so the old
    /// hardcoded path missed them entirely and they hit
    /// `rosterFallbackReason` on every launch.
    ///
    /// Cross-repo sync contract (Plan 4 Task 8):
    ///   * The canonical file lives in scout-plugin and is regenerated by
    ///     `scoutctl connectors snapshot` (default invocation also writes the
    ///     bundled fixture at `ScoutTests/Fixtures/connectors.snapshot.json`
    ///     AND the app resource at `Scout/Resources/connectors.snapshot.json`).
    ///   * scout-plugin CI runs `--check` against
    ///     `engine/scout/connectors.snapshot.json` so YAML edits without a
    ///     regenerated snapshot fail there.
    ///   * If you're editing this resolver, also update the writer in
    ///     `scout-plugin/engine/scout/scripts/connectors_snapshot.py` so
    ///     it keeps targeting all three sinks.
    nonisolated static var defaultSnapshotURL: URL {
        if let bundled = Bundle.main.url(
            forResource: "connectors.snapshot", withExtension: "json"
        ) {
            return bundled
        }
        return FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("scout-plugin/engine/scout/connectors.snapshot.json")
    }

    /// Shape mirroring `connectors.snapshot.json` v1.
    private struct SnapshotFile: Decodable {
        struct Entry: Decodable {
            let key: String
            let display_name: String
            let tier: String
        }
        let schema_version: Int
        let generated_from: String
        let connectors: [Entry]
    }

    /// Failure reason for snapshot loading. Carries a human-readable message
    /// for the operator banner (and logs).
    struct RosterLoadError: Error {
        let message: String
    }

    /// Load the connector roster from a snapshot URL. Returns the array of
    /// canonical keys on success, or a `RosterLoadError` with a human-readable
    /// reason on failure.
    nonisolated static func loadRoster(from url: URL) -> Result<[String], RosterLoadError> {
        guard FileManager.default.fileExists(atPath: url.path) else {
            return .failure(RosterLoadError(message: "snapshot not found at \(url.path)"))
        }
        do {
            let data = try Data(contentsOf: url)
            let parsed = try JSONDecoder().decode(SnapshotFile.self, from: data)
            guard parsed.schema_version == 1 else {
                return .failure(RosterLoadError(message: "unsupported snapshot schema_version=\(parsed.schema_version)"))
            }
            let keys = parsed.connectors.map { $0.key }
            guard !keys.isEmpty else {
                return .failure(RosterLoadError(message: "snapshot contained zero connectors"))
            }
            return .success(keys)
        } catch {
            return .failure(RosterLoadError(message: "failed to decode \(url.lastPathComponent): \(error)"))
        }
    }

    /// Hardcoded fallback used when the snapshot can't be read.
    /// Updated 2026-04-28 (Plan 4 Task 8) to use the canonical YAML keys
    /// (`mcp:claude_ai_Slack`, `mcp:claude_ai_Linear`) — the previous values
    /// (`mcp:plugin_slack_slack`, `mcp:plugin_linear_linear`) never matched
    /// what `connector_health_report.sh` actually emitted, so the rail card
    /// silently showed those rows as dark even when the connectors were fine.
    /// Mirrors the YAML roster (11 connectors, Fathom added 2026-10-03).
    nonisolated static let fallbackConnectors: [String] = [
        "mcp:claude_ai_Slack",
        "mcp:claude_ai_Linear",
        "mcp:claude_ai_Gmail",
        "mcp:claude_ai_Google_Calendar",
        "mcp:claude_ai_Granola",
        "mcp:fathom",
        "mcp:claude_ai_Google_Drive",
        "github",
        "mcp:claude-in-chrome",
        "mcp:whatsapp-mcp",
        "notify:telegram"
    ]

    /// Public default — loads from the canonical snapshot URL. Returns the
    /// fallback list if the snapshot is missing. Used by callers that want a
    /// roster without instantiating the full service.
    nonisolated static var defaultConnectors: [String] {
        switch loadRoster(from: defaultSnapshotURL) {
        case .success(let keys):
            return keys
        case .failure:
            return fallbackConnectors
        }
    }

    func loadInitial() async throws {
        await refresh()
        startWatching()
    }

    func acknowledge(fingerprint: String) {
        ackStore.ack(fingerprint: fingerprint)
        recomputeActiveAlerts(all: allAlertsFromLog())
    }

    // MARK: - Internals

    /// Number of completed reloads. Lets callers (and tests) see that an
    /// append storm coalesced instead of driving one reload per event.
    @Published private(set) var refreshCount: Int = 0

    func refresh() async {
        defer { refreshCount += 1 }
        // 1. Matrix from all connector-calls-*.jsonl in logsDirectory within 14d window.
        let calls = await loadCallsWithinWindow()
        matrix = ConnectorHealthMatrix(calls: calls, connectors: connectors)
        // 2. Alerts from connector-alerts.log.
        let all = allAlertsFromLog()
        recomputeActiveAlerts(all: all)
        // 3. GC ack store against the live fingerprint set.
        ackStore.gc(active: Set(all.map(\.fingerprint)))
    }

    private func allAlertsFromLog() -> [ConnectorAlert] {
        let url = logsDirectory.appendingPathComponent("connector-alerts.log")
        return ConnectorAlert.parseFile(at: url)
    }

    private func recomputeActiveAlerts(all: [ConnectorAlert]) {
        // Deduplicate: keep latest ts per (connector, level).
        var latest: [String: ConnectorAlert] = [:]
        for a in all {
            let key = "\(a.connector)|\(a.level.rawValue)"
            if let existing = latest[key], existing.ts >= a.ts { continue }
            latest[key] = a
        }
        activeAlerts = latest.values
            .filter { !ackStore.isAcked($0.fingerprint) }
            .sorted { $0.ts > $1.ts }
    }

    private func loadCallsWithinWindow() async -> [ConnectorCall] {
        let windowStart = Date().addingTimeInterval(-14 * 24 * 3600)
        // Pick the files by their day *before* reading them. Parsing all
        // history and filtering rows afterwards made every refresh O(all
        // history) — 29k records and ~3.4s on a real logs directory.
        let jsonlURLs = ConnectorCall.logURLs(in: logsDirectory, since: windowStart)

        // Only files whose size/mtime moved need parsing; history is
        // immutable, so a steady append storm re-parses one file, not the
        // whole window. The parse itself stays off this actor.
        let calls = await parseCache.calls(for: jsonlURLs) { stale in
            await Task.detached { () -> [URL: [ConnectorCall]] in
                var acc: [URL: [ConnectorCall]] = [:]
                for url in stale { acc[url] = ConnectorCall.parseFile(at: url) }
                return acc
            }.value
        }
        return calls.filter { $0.ts >= windowStart }
    }

    private func startWatching() {
        watchTask?.cancel()
        // A live Scout run appends to `connector-calls-<today>.jsonl`
        // continuously. Undebounced, every append triggered a full reload and
        // the service could never catch up — observed pinning a core for
        // hours. Same coalescing SessionLogService uses for session logs (#22).
        // Subscribe synchronously so events emitted before the task starts
        // are not dropped.
        let events = DebouncedFileEvents(base: fileEvents, interval: .milliseconds(250))
            .events(for: logsDirectory)
        watchTask = Task { [weak self] in
            for await event in events {
                guard let self else { return }
                let name = event.url.lastPathComponent
                let relevant = name.hasPrefix("connector-calls-")
                    || name == "connector-alerts.log"
                if relevant { await self.refresh() }
            }
        }
    }
}
